//| Copyright - The University of Edinburgh 2011                            |
//|                                                                         |
//| Licensed under the Apache License, Version 2.0 (the "License");         |
//| you may not use this file except in compliance with the License.        |
//| You may obtain a copy of the License at                                 |
//|                                                                         |
//|    http://www.apache.org/licenses/LICENSE-2.0                           |
//|                                                                         |
//| Unless required by applicable law or agreed to in writing, software     |
//| distributed under the License is distributed on an "AS IS" BASIS,       |
//| WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.|
//| See the License for the specific language governing permissions and     |
//| limitations under the License.                                          |
/*******************************************************************************
 * Copyright (c) - The University of Edinburgh 2010
 *******************************************************************************/
package uk.ac.ed.epcc.safe.accounting.properties;


/** Factory for objects that support PropertyTags.
 * @see PropertyTarget
 * @author spb
 *
 */
public interface PropertyTargetFactory {
	/** Produce a PropertyFinder that can find any of the PropertyTags
	 * that can be specified for the objects generated by this type.
	 * The PropertyFinder may also contain additional PropertyTags as well.
	 * 
	 * @return PropertyFinder
	 */
	public PropertyFinder getFinder();
	
	/** Check if the specified property is defined.
	 * All properties that return true MUST be in the set returned by the
	 * getFinder call but this test can be more stringent and can omit a property if
	 * none of the produced objects can generate the specified property.
	 * 
	 * @param <P>
	 * @param tag
	 * @return boolean
	 */
	public <P> boolean hasProperty(PropertyTag<P> tag);
}