//| Copyright - The University of Edinburgh 2015                            |
//|                                                                         |
//| Licensed under the Apache License, Version 2.0 (the "License");         |
//| you may not use this file except in compliance with the License.        |
//| You may obtain a copy of the License at                                 |
//|                                                                         |
//|    http://www.apache.org/licenses/LICENSE-2.0                           |
//|                                                                         |
//| Unless required by applicable law or agreed to in writing, software     |
//| distributed under the License is distributed on an "AS IS" BASIS,       |
//| WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.|
//| See the License for the specific language governing permissions and     |
//| limitations under the License.                                          |
package uk.ac.ed.epcc.safe.accounting;

import uk.ac.ed.epcc.safe.accounting.expr.ExpressionTarget;
import uk.ac.ed.epcc.safe.accounting.properties.PropExpression;
import uk.ac.ed.epcc.safe.accounting.selector.PropertyTargetGenerator;
/** An {@link PropertyTargetGenerator} where the target is an {@link ExpressionTarget}
 * 
 * @author spb
 *
 * @param <T>
 */
public interface ExpressionTargetGenerator<T extends ExpressionTarget> extends PropertyTargetGenerator<T> {
	/** Check if the expression is compatible with this class.
	 * A false value indicates no record can ever evaluate the expression. For example if it includes
	 * properties that are not generated by the class.
	 * 
	 * @param expr
	 * @return boolean
	 */
	public  <I> boolean compatible(PropExpression<I> expr);
}