package uk.ac.ed.epcc.safe.accounting;

import uk.ac.ed.epcc.safe.accounting.expr.ExpressionTarget;
import uk.ac.ed.epcc.safe.accounting.properties.PropExpression;
import uk.ac.ed.epcc.safe.accounting.selector.PropertyTargetGenerator;
/** An {@link PropertyTargetGenerator} where the target is an {@link ExpressionTarget}
 * 
 * @author spb
 *
 * @param <T>
 */
public interface ExpressionTargetGenerator<T extends ExpressionTarget> extends PropertyTargetGenerator<T> {
	/** Check if the expression is compatible with this class.
	 * A false value indicates no record can ever evaluate the expression. For example if it includes
	 * properties that are not generated by the class.
	 * 
	 * @param expr
	 * @return boolean
	 */
	public  <I> boolean compatible(PropExpression<I> expr);
}
